### ISSUE TITLE
font

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/lmnpmtfy.com#3]
The font isn't the same font that npm uses. Include the font somehow!

``` css
@font-face {
  font-family: 'MyWebFont';
  src: url('myfont.woff2') format('woff2'),
       url('myfont.woff') format('woff');
}

body {
  font-family: 'MyWebFont', 'Arial Narrow', sans-serif;
}
```

or

``` css
@import url(//fonts.googleapis.com/css?family=Open+Sans);

body {
  font-family: 'Open Sans', sans-serif;
}
```

**Comment by ArtskydJ** [comment]
``` html
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400' rel='stylesheet' type='text/css'>
<!-- keep ",400" only if you're going to write "npm is the package manager for javascript" using this font -->
```

``` css
body {
    font-family: 'Source Sans Pro', 'Lucida Grande', 'Arial Narrow', sans-serif;
}
input {
    font-weight: 300;
}
```
