### ISSUE TITLE
Update the look & feel

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/lmnpmtfy.com#8]
``` css
body {
    min-width: 1140px;
}

#front-page-container {
    overflow-y: hidden;
    height: calc(100vh - 141px);
}

#main {
    width: 950px;
}
```

``` html
<td>
    <span style="position: relative; top: 10px;">let me</span>
    <img id="logo" src="./img/npm-logo.svg" alt="npm logo">
    <span style="position: relative; top: 10px;">that for you</span>
</td>
```
